import { Story } from '../types';
import { echoStory } from './stories/echoStory';
import { curiStory } from './stories/curiStory';
import { btechStory } from './stories/btechStory';
import { lastTrainStory } from './stories/lastTrainStory';
import { inkStory } from './stories/inkStory';
import { quietStory } from './stories/quietStory';

const rawStories: Story[] = [
  lastTrainStory,
  inkStory,
  quietStory, // Added the new story
  btechStory,
  echoStory,
  curiStory
];

// Helper to get user ratings from local storage
// NOTE: Since this is a client-side app, all persistence is local.
// There are no fake ratings; all displayed ratings are generated by the user.
const getUserRatings = (): Record<string, number> => {
  try {
    const stored = localStorage.getItem('user_ratings');
    return stored ? JSON.parse(stored) : {};
  } catch {
    return {};
  }
};

export const rateStory = (storyId: string, rating: number): void => {
  const ratings = getUserRatings();
  ratings[storyId] = rating;
  localStorage.setItem('user_ratings', JSON.stringify(ratings));
  // Dispatch a custom event to notify components to re-render if needed
  window.dispatchEvent(new Event('ratingUpdated'));
};

export const getSortedStories = (): Story[] => {
  const userRatings = getUserRatings();

  const storiesWithAdjustedRatings = rawStories.map(story => {
    const userRating = userRatings[story.id];
    
    if (userRating) {
      // In this local-only mode, the user's rating is the definitive rating
      // because we initialized all base ratings to 0.
      return {
        ...story,
        rating: userRating,
        reviewCount: 1 // Indicates it has been rated by the user
      };
    }
    
    return story;
  });

  // Sort by rating (descending)
  return storiesWithAdjustedRatings.sort((a, b) => b.rating - a.rating);
};

export const getStory = (id: string) => getSortedStories().find(s => s.id === id);
